// Code generated by goctl. DO NOT EDIT.
package types

type MsgFormat struct {
	Sender    string `json:"sender"`
	Receiver  string `json:"receiver"`
	MsgString string `json:"msgString"`
	Timestamp string `json:"timestamp"`
}
